version: '3'
services:
  app:
    image: node-service:1.4
    container_name: client-service
    ports:
      - 3002:3000
    environment:
      - DB_HOST=database-service
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_NAME=${DATABASE_NAME}
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: database-service
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: