version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=myuser
      - DB_PASSWORD=mypass
      - DB_NAME=mydb
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
      - MYSQL_ROOT_PASSWORD=myrootpass
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: