version: '3.9'

services:
  mongodb:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    ports:
      - 3001:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017
      DB_NAME: sample-db
    depends_on: 
      - mongodb

volumes:
  mongo_data:
